name: Build and publish Docker images

on: workflow_dispatch

jobs:
  build:
    name: "Building and publishing image (${{matrix.compiler.name}})"

    strategy:
      fail-fast: true
      matrix:
        compiler:
          - {name: Clang 18, cc: clang, cxx: clang++, version: 18}
          - {name: Clang 17, cc: clang, cxx: clang++, version: 17}
          - {name: Clang 16, cc: clang, cxx: clang++, version: 16}
          - {name: Clang 15, cc: clang, cxx: clang++, version: 15}

    runs-on: ubuntu-latest

    env:
      IMAGE_BASENAME: educontainer

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build --tag "${{vars.HUB_USERNAME}}/${{env.IMAGE_BASENAME}}:${{matrix.compiler.cc}}${{matrix.compiler.version}}" --build-arg COMPILER_NAME=${{matrix.compiler.cc}} --build-arg COMPILER_NAMEXX=${{matrix.compiler.cxx}} --build-arg COMPILER_VERSION=${{matrix.compiler.version}} .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}
      - name: Publish to Docker Hub
        run: docker push "${{vars.HUB_USERNAME}}/${{env.IMAGE_BASENAME}}:${{matrix.compiler.cc}}${{matrix.compiler.version}}"
