name: Build and test Docker images

on: push

env:
  RUN_TESTS: true
  BASE_IMAGE_NAME: "${{ vars.HUB_USERNAME }}/educontainer"

jobs:
  ubuntu-gcc:
    name: "Building and testing image (Ubuntu: GCC ${{ matrix.version }})"

    strategy:
      fail-fast: true
      matrix:
        version:
          - 13
          - 12
          - 11
          - 10
          - 9

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and test
        run: bash extra/buildtest.sh "gcc" "g++" "${{ matrix.version }}"

  ubuntu-clang:
    name: "Building and testing image (Ubuntu: Clang ${{ matrix.version }})"

    strategy:
      fail-fast: true
      matrix:
        version:
          - 18
          - 17
          - 16
          - 15

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and test
        run: bash extra/buildtest.sh "clang" "clang++" "${{ matrix.version }}"

  windows-msvc:
    name: "Building and testing image (Windows: MSVC ${{ matrix.version }})"

    strategy:
      fail-fast: true
      matrix:
        version:
          - 17
          # - 16
          # - 15

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4
      - name: Build and test
        run: powershell .\extra\buildtest.ps1 "msvc" "${{ matrix.version }}"
