name: Build and test Docker images

on: push

env:
  RUN_TESTS: true
  BASE_IMAGE_NAME: "${{ vars.HUB_USERNAME }}/educontainer"

jobs:
  ubuntu-gcc:
    name: "Building and testing image (Ubuntu: GCC ${{ matrix.version }})"

    strategy:
      fail-fast: true
      matrix:
        version:
          - 13
          - 12
          - 11
          - 10
          - 9

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and test
        run: bash extra/buildtest.sh "gcc" "g++" "${{ matrix.version }}"

  ubuntu-clang:
    name: "Building and testing image (Ubuntu: Clang ${{ matrix.version }})"

    strategy:
      fail-fast: true
      matrix:
        version:
          - 18
          - 17
          - 16
          - 15

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and test
        run: bash extra/buildtest.sh "clang" "clang++" "${{ matrix.version }}"

  windows:
    name: "Building and testing image (Windows: ${{ matrix.os.name }}, ${{ matrix.compiler.name }})"

    strategy:
      fail-fast: true
      matrix:
        compiler:
          - { name: MSVC, cc: cl }

        os:
          - { name: LTSC 2019, sys: ltsc, version: 2019 }

    runs-on: windows-2019

    env:
      BASE_IMAGE_TAG: "${{ matrix.os.sys }}${{ matrix.os.version }}-${{ matrix.compiler.cc }}"

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build --tag "${{ env.BASE_IMAGE_NAME }}:${{ env.BASE_IMAGE_TAG }}" --build-arg RUN_TESTS=${{ env.RUN_TESTS }} -f windows/Dockerfile .
